import typing
import re
from .genuine import unravel_hierarchical_fields

fb_list_usernames = ['1LIVE',
                     '12-App',
                     '20 Minuten',
                     '3sat',
                     'Aachener Nachrichten',
                     'Aachener Zeitung',
                     'Aarauer Nachrichten',
                     'Aargauer Zeitung',
                     'Abendzeitung München',
                     'Achgut.com - Die Achse des Guten',
                     'Achtzig - Die Kulturzeitung',
                     'actu.fr',
                     'Adpunktum',
                     'Advantage Wirtschaftsmagazin',
                     'Aichacher Zeitung',
                     'Aktuell Obwalden',
                     'Alfelder Zeitung',
                     'all-in.de - das Allgäu online.',
                     'Allgäuer Zeitung',
                     'Allgemeine Zeitung',
                     'Allgemeine Zeitung | Coesfeld | Billerbeck | Gescher | Rosendahl | azonline',
                     'Alpenparlament.TV',
                     'Alpenschau.com',
                     'Andelfinger Zeitung',
                     'annabelle',
                     'Antenne Brandenburg',
                     'Anzeiger Aarberg',
                     'Anzeiger für Harlingerland',
                     'Anzeiger Luzern',
                     'Anzeiger Michelsamt',
                     'Anzeiger vom Rottal',
                     'Anzeiger von Saanen',
                     'Apolut',
                     'Apropos. Salzburger Straßenzeitung',
                     'ARD Mediathek & Das Erste',
                     'Arte',
                     'ATV',
                     'Augsburger Allgemeine',
                     'Augustin Boulevardzeitung',
                     'AZ-Online',
                     'B.Z.',
                     'bachheimer.com',
                     'Backnanger Kreiszeitung',
                     'Badener Tagblatt',
                     'Badener Zeitung',
                     'Badische Zeitung',
                     'Bärnerbär - Berns Wochenzeitung',
                     'Barni-Post AG',
                     'Basler Zeitung',
                     'Bauernzeitung',
                     'Bayerische Staatszeitung',
                     'BAYERN 1',
                     'Bayern 2',
                     'Beobachter',
                     'Berchtesgadener Anzeiger',
                     'Bergedorfer Zeitung',
                     'Berlin Journal',
                     'Berliner Kurier',
                     'Berliner Morgenpost',
                     'Berliner Zeitung',
                     'Berner Landbote',
                     'Berner Zeitung',
                     'Bewusst.TV',
                     'BGLand24',
                     'BIBER',
                     'Bieler Tagblatt',
                     'Bietigheimer Zeitung',
                     'BILANZ',
                     'Bild',
                     'BILD Sport',
                     'BILDblog',
                     'Blaue Narzisse',
                     'Blick',
                     'Blue News',
                     'bnn.de / Baden-Baden, Rastatt, Gaggenau, Murgtal',
                     'bnn.de / Badische Neueste Nachrichten',
                     'Bocholter-Borkener Volksblatt',
                     'Böhme-Zeitung',
                     'Borkener Zeitung',
                     'Börsen-Kurier',
                     'Börsen-Zeitung',
                     'Bote der Urschweiz',
                     'Boyens Medien',
                     'BR - Bayerischer Rundfunk',
                     'BR Franken - Bayerischer Rundfunk',
                     'BR-KLASSIK',
                     'BR24',
                     'Braunschweiger Zeitung',
                     'Bremen Eins',
                     'bremen NEXT',
                     'Bremen Vier',
                     'Bremen Zwei',
                     'Bremervörder Zeitung',
                     'BSAktuell',
                     'BUNTE.de',
                     'Business Insider Deutschland',
                     'BVZ',
                     'bz Zeitung für die Region Basel',
                     'Campact e.V.',
                     'Cannstatter und Untertürkheimer Zeitung',
                     'cash.ch',
                     'Cellesche Zeitung',
                     'chiemgau24',
                     'CHIP',
                     'Cicero',
                     'Cointelegraph auf Deutsch. Blockchain und Bitcoin Nachrichten',
                     'come-on.de',
                     'COMPUTER BILD',
                     'COMPUTERWOCHE',
                     'Computerworld.ch',
                     'Confidencial Digital',
                     'Coopzeitung',
                     'Cosmo',
                     'Cuxhavener Nachrichten',
                     'Das Lamm',
                     'Das Magazin',
                     'Das Magazin für Patrioten',
                     'DASDING',
                     'Datum',
                     'Delmenhorster Kreisblatt',
                     'Der Bund',
                     'Der Ennstaler',
                     'der Freitag',
                     'Der Funke',
                     'der Grazer',
                     'Der Landanzeiger',
                     'Der Postillon',
                     'DER SPIEGEL',
                     'DER STANDARD',
                     'Der Unter-Emmentaler',
                     'Der Wächter',
                     'Der Westen',
                     'Deutsche Presse-Agentur',
                     'Deutsche Wirtschafts Nachrichten',
                     'Deutschlandfunk',
                     'Deutschlandfunk Kultur',
                     'Deutschlandfunk Nova',
                     'Dewezet',
                     'Diario SUR',
                     'Die Furche',
                     'Die Glocke',
                     'Die Harke - Nienburger Zeitung',
                     'Die Monatliche',
                     'DIE NECKARQUELLE',
                     'Die Oberbadische - Markgräfler Tagblatt - Weiler Zeitung',
                     'Die Presse',
                     'DIE RHEINPFALZ',
                     'Die Tagespost - Katholische Zeitung für Politik, Gesellschaft und Kultur',
                     'Die Tagesstimme',
                     'DIE WELTWOCHE',
                     'Die Wochenzeitung - WOZ',
                     'DIE ZEIT',
                     'Die Zürcherin',
                     'DieUnbestechlichen.com',
                     'Digital Sevilla',
                     'Diözese Eisenstadt',
                     'Direktno.hr',
                     'DNN Dresdner Neueste Nachrichten',
                     'Donau Zeitung',
                     'donaukurier',
                     'dorfheftli',
                     'Dossier',
                     'Dülmener Zeitung',
                     'DW Deutsche Welle',
                     'DW News',
                     'e-media',
                     'Echo Online',
                     'echo24.de',
                     'Economía Digital',
                     'eigentümlich frei',
                     'ein.prozent',
                     'Einbecker Morgenpost',
                     'Eingeschenkt.tv',
                     'Einsiedler Anzeiger',
                     'El Comercio (Diario de Asturias)',
                     'El Confidencial',
                     'El Correo',
                     'El Correo de Andalucía',
                     'El Correo de España',
                     'El Correo Gallego',
                     'El Día - Tenerife',
                     'El Digital Castilla-La Mancha',
                     'El Economista',
                     'El Español',
                     'El Mundo',
                     'El Nacional',
                     'El Norte de Castilla',
                     'El Periódico',
                     'El Periódico Extremadura',
                     'El Plural',
                     'El Punt Avui',
                     'El Tiempo',
                     'Elbe Jeetzel Zeitung',
                     'elboletin.com',
                     'elDiario.es',
                     'eldiariomontanes.es',
                     'Emder Zeitung',
                     'Engadiner Post',
                     'Ennsseiten Wochenzeitung',
                     'Ensonhaber',
                     'Entlebucher Anzeiger',
                     'Erzdiözese Salzburg',
                     'Eßlinger Zeitung',
                     'ESdiario',
                     'Estrella Digital',
                     'Euronews Deutsch',
                     'Europa Press',
                     'Europe 1',
                     'ExoMagazin.tv',
                     'Expansión.com',
                     'EXPRESS',
                     'Express & Star',
                     'Extratipp',
                     'ExtremNews',
                     'Falter. Die Wochenzeitung aus Wien.',
                     'Fanpage.it',
                     'FAZ.NET - Frankfurter Allgemeine Zeitung',
                     'Fdesouche',
                     'Fehmarn/Heiligenhafen24',
                     'Femina',
                     'Financial Times',
                     'Finanz und Wirtschaft',
                     'finanzen.ch',
                     'finanzen.net',
                     'FinanzNachrichten.de',
                     'finews.ch',
                     'First Coast News',
                     'FischundFleisch',
                     'FiveThirtyEight',
                     'Flensborg Avis',
                     'Flensburger Tageblatt',
                     'FM1Today',
                     'FNP - Frankfurter Neue Presse',
                     'FOCUS online',
                     'Forbes DA',
                     'Fortune',
                     'FOX',
                     'Fox 11 Los Angeles',
                     'FOX 13 News',
                     'FOX 13 News - Tampa Bay',
                     'Fox 8 News',
                     'Fox 9',
                     'Fox Business',
                     'Fox News',
                     'Fox2Now',
                     'FOX4 News Kansas City',
                     'FOX59 News',
                     'FOX6 News Milwaukee',
                     'FRANCE 24 English',
                     'France 3',
                     'France Bleu',
                     'France Culture',
                     'France Inter',
                     'France Télévisions',
                     'france.tv',
                     'Franceinfo',
                     'FranceSoir',
                     'Frankenpost',
                     'Frankfurter Rundschau',
                     'Fränkische Landeszeitung',
                     'Fränkische Nachrichten',
                     'Frapp Freiburg',
                     'Frauenfelder Woche',
                     'Free21',
                     'Freiburger Nachrichten',
                     'Freie Medien',
                     'Freie Presse',
                     'Freie Welt',
                     'Freier Schweizer',
                     'FreieSicht.Org',
                     'Freitags-Anzeiger',
                     'Freitum',
                     'fricktal.info',
                     'Fritz',
                     'Fuldaer Zeitung',
                     'futurezone.at',
                     'Gala',
                     'Gandersheimer Kreisblatt',
                     'Gasteiz Hoy',
                     'Gäubote',
                     'Gazzetta del Sud',
                     'Gazzetta di Parma',
                     'gegenargument.at',
                     'Gelnhäuser Neue Zeitung',
                     'Gelnhäuser Tageblatt',
                     'General-Anzeiger',
                     'General-Anzeiger Bonn',
                     'Geolitico',
                     'germanforeignpolicy.com',
                     'GHI - Le Journal indépendant des Genevois',
                     'Gießener Allgemeine Zeitung',
                     'Gießener Anzeiger',
                     'Giornale di Brescia',
                     'Giornalone',
                     'Gk Digital',
                     'Glasgow Times',
                     'GlücksPost',
                     'Gmünder Tagespost',
                     'GMX News',
                     'Golem.de',
                     'Good Morning America',
                     'Google News',
                     'Goslarsche Zeitung',
                     'Göttinger Tageblatt',
                     'Grafschafter Nachrichten',
                     'Granada Hoy',
                     'Grant Thornton Czech Republic',
                     'Graswurzelrevolution',
                     'Grenchner Tagblatt',
                     'Haberler.com',
                     'Haller Kreisblatt',
                     'Haller Tagblatt - Südwest Presse',
                     'Hallo München',
                     'hallowil.ch',
                     'Hamburger Abendblatt',
                     'Hamburger Morgenpost',
                     'Hanauer Anzeiger',
                     'Handelsblatt',
                     'Handelszeitung',
                     'Hannoversche Allgemeine Zeitung / HAZ',
                     'Harz Kurier',
                     'Heidelberg24',
                     'Heidenheimer Zeitung',
                     'Heilbronner Stimme',
                     'heise online',
                     'Hellweger Anzeiger',
                     'Heraldo de Aragón',
                     'Hersbrucker Zeitung',
                     'Hersfelder Zeitung',
                     'Hertener Allgemeine',
                     'hessenschau',
                     'Heute',
                     'hildesheimer-allgemeine.de',
                     'Hintergrund - Das Nachrichtenmagazin',
                     'HLN.be',
                     'HNA',
                     'Höngger Quartierzeitung',
                     'HORIZONT Österreich',
                     'HOY.es',
                     'hr-fernsehen',
                     'hr1',
                     'hr3',
                     'https://www.facebook.com/Cashkurs',
                     'Huelva Información',
                     'HuffPost',
                     'Hull Live',
                     'Ibbenbürener Volkszeitung',
                     'Ideal.es',
                     'idowa.de',
                     'Il Corriere della Città',
                     'Il Fatto Quotidiano',
                     'Il Foglio',
                     'Il Gazzettino',
                     'Il Giornale',
                     'Il Grigione Italiano',
                     'il manifesto',
                     'Il Messaggero',
                     'Il Primato Nazionale',
                     'Imprimerie Le Franc-Montagnard',
                     'Infosperber',
                     'inFranken.de',
                     'innsalzach24',
                     'inside-it.ch',
                     'inSüdthüringen',
                     'Internetz-Zeitung.eu',
                     'Jeversches Wochenblatt',
                     'Journal de Cossonay',
                     'Journal de Morges',
                     'Journal de Sierre',
                     'Journal21',
                     'Jouwatch',
                     'JUNGE FREIHEIT',
                     'junge Welt',
                     'Jungfrau Zeitung',
                     'ka-news.de',
                     'Kabel Eins',
                     'Kanal9',
                     'Kärntner MONAT',
                     'kath.ch',
                     'Kevelaerer Blatt',
                     'Kieler Nachrichten',
                     'Kirche bunt',
                     'KirchenZeitung Diözese Linz',
                     'Kleine Zeitung',
                     'Klettgauer Bote',
                     'Klotener Anzeiger',
                     'Kölnische Rundschau',
                     'konkret',
                     'KONSUMENT',
                     'kontrast.at',
                     'Krautreporter',
                     'Kreis-Anzeiger',
                     'Kreiszeitung Böblinger Bote',
                     'Kreiszeitung Wesermarsch',
                     'Kreiszeitung Wochenblatt',
                     'kreiszeitung.de',
                     'Kreuzlinger Zeitung',
                     'Krisenfrei Community',
                     'Kronen Zeitung',
                     'KSTA',
                     'KURIER',
                     "L'Eco di Bergamo",
                     "L'Est Républicain",
                     "l'Humanité",
                     "L'illustré",
                     'La Côte',
                     'La Gaceta de la Iberosfera',
                     'La Gruyère',
                     'La Télé',
                     'LaBroye Hebdo',
                     'Lahrer Zeitung',
                     'Landbote',
                     'Landeszeitung Lüneburg',
                     'Landshuter Zeitung',
                     'LAOLA1',
                     'laRegione',
                     'Lausitzer Rundschau',
                     'Lauterbacher Anzeiger',
                     'Le Courrier',
                     'Le Monde',
                     'Le Nouvelliste',
                     'Le Quotidien Jurassien',
                     'Le Temps',
                     'legitim.ch',
                     'leinetal24.de',
                     'Léman Bleu',
                     'LeMatin.ch',
                     'Leonberger Kreiszeitung',
                     'LFM - La Radio',
                     'Liberale Warte',
                     'Liechtensteiner Vaterland',
                     'Liechtensteiner Volksblatt',
                     'Limmattaler Zeitung',
                     'Links-Netz',
                     'Linksnet',
                     'Linth-Zeitung',
                     'Lippische Landes-Zeitung',
                     'LN Medienhaus',
                     'Lokal26',
                     'London Evening Standard',
                     'Lübecker Nachrichten Online',
                     'Ludwigsburger Kreiszeitung | www.lkz.de',
                     'Luzerner Rundschau',
                     'Luzerner Zeitung',
                     'LVZ Leipziger Volkszeitung',
                     'Main-Echo',
                     'Main-Post',
                     'manager magazin',
                     'Mannheimer Morgen',
                     'March24 & Höfe24',
                     'Märkische Onlinezeitung MOZ.de',
                     'MAZonline / Märkische Allgemeine',
                     'MDR - Mitteldeutscher Rundfunk',
                     'MDR AKTUELL',
                     'MDR JUMP',
                     'MDR KULTUR',
                     'MDR Sachsen',
                     'MDR Sachsen-Anhalt',
                     'MDR SPUTNIK',
                     'MDR Thüringen',
                     'Mediaset Infinity',
                     'Medienwoche',
                     'MEGAPHON',
                     'MeinBezirk.at - Österreichweite Nachrichten',
                     'Merkur.de',
                     'Mindelheimer Zeitung',
                     'Mindener Tageblatt',
                     'Mittelbadische Presse - Zeitungen der Ortenau',
                     'Mittelbayerische',
                     'Mitteldeutsche Zeitung',
                     'mittelhessen.de',
                     'MMnews',
                     'Mosaik - Politik neu zusammensetzen',
                     'MSN',
                     'Mühlacker Tagblatt',
                     'Münsterland Zeitung',
                     'Münstersche Zeitung',
                     'MV digital',
                     'MV.TV',
                     'MYTF1',
                     'N-JOY',
                     'n-land.de',
                     'NachDenkSeiten',
                     'Nau.ch',
                     'NDR 2',
                     'NDR Hamburg',
                     'NDR Info',
                     'NDR Kultur',
                     'NDR Mecklenburg-Vorpommern',
                     'NDR Niedersachsen',
                     'NDR Schleswig-Holstein',
                     'NDR.de',
                     'NDTV',
                     'NECKAR-CHRONIK',
                     'NEOPresse - Unabhängige Nachrichten',
                     'Netzfrauen',
                     'Neue Deister-Zeitung / NDZ',
                     'Neue Fricktaler Zeitung',
                     'Neue Oberaargauer Zeitung',
                     'Neue Oltner Zeitung',
                     'Neue Presse Coburg',
                     'Neue Presse Hannover / NP',
                     'NEUE Vorarlberger Tageszeitung',
                     'Neue Westfälische',
                     'neues deutschland',
                     'News 12',
                     'News 5 Cleveland',
                     'News Mondo',
                     'News Republic',
                     'news.at',
                     'news.ch',
                     'news.com.au',
                     'news.de',
                     'news38.de',
                     'NEWSbreak24.de',
                     'Newsday',
                     'Newser',
                     'Newsweek',
                     'Next quotidiano',
                     'Niederelbe-Zeitung',
                     'nnn.de - Nachrichten aus Rostock und Umgebung',
                     'NNP - Nassauische Neue Presse',
                     'No Islam Italia',
                     'NÖN',
                     'Nordbayerischer Kurier',
                     'nordbayern.de',
                     'Nordkurier',
                     'Nordsee-Zeitung',
                     'Novo - Argumente für den Fortschritt',
                     'noz.de',
                     'NPR',
                     'Npr.news',
                     'NRZ',
                     'ntv Nachrichten',
                     'Nürnberger Nachrichten',
                     'Nürtinger Zeitung',
                     'NWZonline',
                     'NZZ am Sonntag',
                     'NZZ Neue Zürcher Zeitung',
                     'Oberhessische Presse',
                     'Oberhessische Zeitung',
                     'Obermain Tagblatt',
                     'Obersee Nachrichten',
                     'Obersteirische Rundschau',
                     'Obwaldner Zeitung',
                     'oe24.at',
                     'oe24.tv',
                     'Offenburger Tageblatt / Kinzigtalausgabe',
                     'Oltner Tagblatt',
                     'OM Online',
                     'Onetz',
                     'Online-Magazin Erstaunlich',
                     'OÖNachrichten',
                     'op-online.de',
                     'ORF',
                     'Österreichische BauernZeitung',
                     'Ostfriesen-Zeitung',
                     'Ostfriesische Nachrichten',
                     'osthessen-news.de',
                     'Osthessen-Zeitung',
                     'Ostsee-Zeitung',
                     'OTZ',
                     'OVB Heimatzeitungen',
                     'Pappenheimer Skribent',
                     'Passauer Neue Presse - PNP',
                     'PAZ Peiner Allgemeine Zeitung',
                     'PBS',
                     'PCtipp.ch',
                     'persönlich',
                     'Perspective Daily',
                     'Pfälzischer Merkur',
                     'Pharmazeutische Zeitung',
                     'PHOENIX',
                     'Pinneberger Tageblatt',
                     'Pirmasenser Zeitung',
                     'PME',
                     'PME News - O Portal da Micro, Pequena e Média Empresa',
                     'Pocket',
                     'POLIZEI-SCHWEIZ.ch',
                     'Potsdamer Neueste Nachrichten',
                     'Pressecop24.com',
                     'presseportal',
                     'Preussischer Anzeiger',
                     'Prima Lecco',
                     'Prima Monza',
                     'Prime News',
                     'profil',
                     'Promiflash',
                     'propagandafront',
                     'ProSieben',
                     'PULS24NEWS',
                     'PZ-news.de',
                     'qpress.de • die 4/2 Wahrheiten',
                     'QUOTIDIEN LA LIBERTÉ',
                     'Radio BAYERN 3',
                     'Radio Hochstift',
                     'Radio MK',
                     'RADIO TELEVISION SUISSE (RTS)',
                     'Radio Utopie',
                     'radioeins',
                     'rbb 88.8',
                     'rbbKultur',
                     'Recklinghäuser Zeitung',
                     'Rems-Zeitung',
                     'Remscheider General-Anzeiger',
                     'Reportagen',
                     'Republik',
                     'Reuters',
                     'Reuters News Deutschland',
                     'Reutlinger General-Anzeiger',
                     'RFJ.CH',
                     'Rheiderland Zeitung',
                     'Rhein-Neckar-Zeitung',
                     'Rhein-Zeitung',
                     'Rheingau Echo',
                     'Rheinische Post',
                     'rheintal24.ch',
                     'rheintaler.ch',
                     'Rivista di Lugano',
                     'RJB.ch',
                     'RNF',
                     'rontaler.ch',
                     'rosenheim24',
                     'Rote Fahne News',
                     'rro - radio rottu oberwallis',
                     'RSInews',
                     'RT',
                     'RT DE',
                     'RTL',
                     'RTL Aktuell',
                     'RTL Exclusiv',
                     'RTL WEST',
                     'RTL+',
                     'RTLSport',
                     'RTLZWEI',
                     'RTR Radiotelevisiun Svizra Rumantscha',
                     'Ruhr Nachrichten',
                     'RUHR24.de',
                     'Saarbrücker Zeitung',
                     'Sächsische.de',
                     'Saldo',
                     'SALZBURG24',
                     'Salzburger Nachrichten',
                     'salzi.at - Aktuelles aus dem Salzkammergut',
                     'Salzkammergut-Rundblick',
                     'Sarganserländer',
                     'SAT.1',
                     'Schaffhauser AZ',
                     'Schaffhauser Bock / Schaffhausen24',
                     'Schaffhauser Nachrichten',
                     'Schaumburger Nachrichten',
                     'Schaumburger Zeitung / Schaumburg-Lippische Landes-Zeitung',
                     'Schifferstadter Tagblatt',
                     'Schwäbische',
                     'Schwäbische Post',
                     'Schwäbisches Tagblatt Tübingen',
                     'Schwarzwälder Bote',
                     'Schweizer Bauer',
                     'Schweizer Illustrierte',
                     'Schweizerische Ärztezeitung',
                     'Schweizerzeit',
                     'Seetaler Bote',
                     'Sempacher Woche',
                     'Serbske Nowiny',
                     'Sezession',
                     'shz.de - Nachrichten aus Schleswig-Holstein',
                     'Siegener Zeitung',
                     'SIMMENTAL ZEITUNG',
                     'Sindelfinger Zeitung / Böblinger Zeitung (SZ/BZ)',
                     'Sky Deutschland',
                     'Sky Sport DE',
                     'Slate.com',
                     'Slate.fr',
                     'Soester Anzeiger',
                     'Solinger Tageblatt',
                     'Solothurner Zeitung',
                     'Sonntagsblatt',
                     'SonntagsZeitung',
                     'South Florida Sun Sentinel',
                     'Spektrum der Wissenschaft',
                     'SPIEGEL.TV',
                     'Splinter',
                     'SPORT BILD',
                     'sport.ch',
                     'Sport.de',
                     'SPORT1',
                     'SPORT1eSPORTS',
                     'Sportschau',
                     'Sputnik',
                     'SR 1',
                     'SR 2 KulturRadio',
                     'SR 3 Saarlandwelle',
                     'SRF News',
                     'SRF Schweizer Radio und Fernsehen',
                     'St.Galler-, Gossauer- und Herisauer Nachrichten',
                     'Stadt-Anzeiger Opfikon',
                     'Stadtanzeiger Olten',
                     'Star Tribune',
                     'stern',
                     'Straubinger Tagblatt',
                     'StrettoWeb',
                     'Stuttgarter Nachrichten',
                     'Stuttgarter Zeitung',
                     'Süddeutsche Zeitung',
                     'Süddeutsche Zeitung Magazin',
                     'Süddeutsche Zeitung München',
                     'Sudinfo.be',
                     'SÜDKURIER',
                     'Südostschweiz',
                     'SudOuest.fr',
                     'Südwest Presse',
                     'Surseer Woche',
                     'svz.de - Nachrichten aus Mecklenburg-Vorpommern',
                     'swissinfo.ch auf Deutsch',
                     'SWR Aktuell',
                     'SWR1 Baden-Württemberg',
                     'SWR1 Rheinland-Pfalz',
                     'SWR2',
                     'SWR3',
                     'SWR4 Baden-Württemberg',
                     'SWR4 Rheinland-Pfalz',
                     'SZ Dachau',
                     'SZ Ebersberg',
                     'SZ Freising',
                     'SZ Fürstenfeldbruck',
                     't3n Magazin',
                     'TA Thüringer Allgemeine',
                     'TAG24',
                     'TAG24 Berlin',
                     'TAG24 Bielefeld',
                     'TAG24 Chemnitz',
                     'TAG24 Dresden',
                     'TAG24 Erfurt',
                     'TAG24 Erzgebirge',
                     'TAG24 Frankfurt/Main',
                     'TAG24 Gera',
                     'TAG24 Hamburg',
                     'TAG24 Jena',
                     'TAG24 Köln',
                     'TAG24 Leipzig',
                     'TAG24 Magdeburg',
                     'TAG24 Minden',
                     'TAG24 München',
                     'TAG24 Paderborn',
                     'TAG24 Stuttgart',
                     'TAG24 Vogtland',
                     'TAG24 Zwickau',
                     'Tagblatt',
                     'Tagblatt der Stadt Zürich',
                     'Tageblatt',
                     'TAGEBLATT online',
                     'Tages-Anzeiger',
                     'tagesschau',
                     'Tagesspiegel',
                     'Täglicher Anzeiger Holzminden',
                     'taz',
                     'TechCrunch',
                     'Teckbote',
                     'Tele 1',
                     'Tele M1',
                     'TeleBärn',
                     'Telebasel',
                     'TeleBielingue',
                     'Telecinco',
                     'Telegraf Najnovije Vesti',
                     'Telegrafi.com',
                     'Telemundo',
                     'Telepolis',
                     'TeleTicino',
                     'TeleZüri',
                     'Tempi',
                     'Termometro Politico',
                     'Tessiner Zeitung',
                     'Tgcom24',
                     'The Chicago Sun-Times',
                     'The Economist',
                     'The Epoch Times',
                     'The European',
                     'The Independent',
                     'The New York Times',
                     'The New Yorker',
                     'The Oklahoman',
                     "The People's Voice",
                     'The Telegraph',
                     'The Telegraph & macon.com',
                     'The Wall Street Journal',
                     'The Washington Times',
                     'The Western Journal',
                     'Thüringische Landeszeitung - TLZ',
                     'Tichys Einblick',
                     'Tips.at',
                     'Tiroler Tageszeitung',
                     'Traunsteiner Tagblatt',
                     'Trentino',
                     'Trostberger Tagblatt',
                     'TV5MONDE',
                     'TVO - Das Ostschweizer Fernsehen',
                     'tz München',
                     'U.S. News and World Report',
                     'Übermedien',
                     'UdineToday',
                     'Uetersener Nachrichten',
                     'UFA-Revue',
                     'UKTV Play',
                     'UN - Unabhängige Nachrichten',
                     'Unser Mitteleuropa',
                     'Unsere Zeit',
                     'Unsere Zeitung',
                     'Unterkärntner Nachrichten',
                     'Unterland Zeitung',
                     'unzensuriert.at',
                     'unzensuriert.de',
                     'UOL',
                     'Urner Wochenblatt',
                     'Urner Zeitung',
                     'USA TODAY',
                     'USA TODAY Sports',
                     'Usinger Anzeiger',
                     'Vaihinger Kreiszeitung',
                     'Valencia Plaza',
                     'Valeurs actuelles',
                     'Ve_ernje novosti',
                     'Vesti-OnLine.com',
                     'VICE',
                     'VICE auf Deutsch',
                     'VIENNA.AT - Vienna Online',
                     'VilaWeb',
                     'Voice of America',
                     'VOL.AT - Vorarlberg Online',
                     'Volketswiler Nachrichten',
                     'volksblatt.at',
                     'volksfreund.de',
                     'Volksstimme.ch',
                     'Volksstimme.de',
                     'Volksverpetzer',
                     'Vorarlberger Nachrichten',
                     'Votum24',
                     'VOX',
                     'Vozpópuli',
                     'VRM',
                     'WA',
                     'Walsroder Zeitung',
                     'WANN & WO Die junge Zeitung',
                     'Washington Examiner',
                     'Washington Post',
                     'watson',
                     'watson.de',
                     'WAZ',
                     'WAZ Bochum',
                     'WAZ Essen',
                     'WAZ Wolfsburger Allgemeine Zeitung',
                     'WDR',
                     'WDR 2',
                     'WDR 3',
                     'WDR 4',
                     'WDR aktuell',
                     'WDR Lokalzeit Bergisches Land',
                     'WDR Lokalzeit Ruhr',
                     'WEAU 13 News',
                     'Weekend Magazin',
                     'WELT',
                     'Welt der Frauen',
                     'WELT Nachrichtensender',
                     'Weltnetz.TV',
                     'Werdenberger & Obertoggenburger',
                     'Werdener Nachrichten',
                     'Werra-Rundschau',
                     'WESER-KURIER',
                     'Westfalen-Blatt',
                     'Westfalenpost Hagen',
                     'Westfälische Nachrichten',
                     'Wetterauer Zeitung',
                     'Wetzlarer Neue Zeitung - mittelhessen.de',
                     'Wiener - Alles für Er.',
                     'Wiener Zeitung',
                     'WIENERIN',
                     'Wiesbadener Kurier',
                     'Wiler Nachrichten',
                     'Willisauer Bote',
                     'Winsener Anzeiger',
                     'Winterthurer Zeitung',
                     'WIRED',
                     'Wired Italia',
                     'Wirtschaftsmagazin GEWINN',
                     'WirtschaftsWoche',
                     'WIRTSCHAFTSZEIT',
                     'WJXT4 The Local Station / News4JAX',
                     'WLZ / Waldeckische Landeszeitung',
                     'wn24 Wiener Neustadt. Aktuell.',
                     'wnoz',
                     'Wochen-Post',
                     'Wochen-Zeitung für das Emmental & Entlebuch',
                     'Wochenblatt Landshut',
                     'Wochenblatt Straubing',
                     'Wochenblick',
                     'Wohler Anzeiger / Bremgarter Bezirks-Anzeiger / Der Freiämter',
                     'Wolfsburger Nachrichten',
                     'WOMAN',
                     'WSB-TV',
                     'Wümme-Zeitung',
                     'www.regionews.at',
                     'WXYZ-TV Channel 7',
                     'WZ - Westdeutsche Zeitung',
                     'Yahoo Deutschland',
                     'Yahoo News',
                     'YOU FM',
                     'ZAROnews Presse & PR',
                     'ZDF',
                     'ZEIT ONLINE',
                     'Zeitlupe',
                     'Zeitungsverlag Der Patriot',
                     'Zeitungsverlag Waiblingen',
                     'zentralplus',
                     'Zevener Zeitung',
                     'Zillertaler Zeitung',
                     'Zofinger Tagblatt / zt',
                     'ZOLLERN-ALB-KURIER',
                     'ZueriToday',
                     'ZUERST! – Deutsches Nachrichtenmagazin',
                     'Zuger Presse / Zugerbieter',
                     'Zuger Woche',
                     'Zur Zeit',
                     'Zürcher Unterländer',
                     'Zürichsee-Zeitung',
                     'Züriost']


def fb_anonymize_generic(field: str, sep_strings: list) -> str:
    for sep_string in sep_strings:
        if sep_string[0] in field and sep_string[1] in field:
            names, rest = field.split(sep_string[0])
            rest_2 = rest.split(sep_string[1])[0].strip()
            if any(re.match(rest_2 + "?", item) for item in fb_list_usernames):
                return field.replace(names, "<user> ")
            else:
                return field.replace(names, "<user> ").replace(rest_2, "<other>")
    return field


async def fb_anonymize_reactions(entry: typing.Dict[str, typing.Any], _: str = '') -> typing.Dict[str, typing.Any]:
    if "title" in entry:
        sep_strings = [
            # en
            ["likes", "own post."],
            ["liked", "own post."],
            ["likes", "this."],
            ["liked", "this."],
            ["likes", "post."],
            ["liked", "post."],
            ["likes", "post in"],
            ["liked", "post in"],
            ["likes", "photo."],
            ["liked", "photo."],
            ["likes", "comment."],
            ["liked", "comment."],
            ["likes", "video."],
            ["liked", "video."],
            ["reacted to", "post."],
            ["reacted to", "comment."],

            # de
            ["gefällt", "eigenen Chronik."],
            ["gefällt", "Beitrag"],
            ["gefällt", "Beitrag in"],
            ["gefällt", "Beitrag auf"],
            ["gefällt", "Kommentar."],
            ["gefällt", "Foto."],
            ["gefällt", "Video."],
            ["hat", "Beitrag reagiert."],
            ["hat", "Kommentar reagiert."]
        ]
        entry["title"] = fb_anonymize_generic(entry['title'], sep_strings)
    return entry


async def fb_anonymize_comments(entry: typing.Dict[str, typing.Any], comment_field: str = '') \
        -> typing.Dict[str, typing.Any]:
    if comment_field in entry:
        sep_strings = [
            # en
            ["commented", "own post."],
            ["replied", "own comment."],
            ["replied to", "comment."],
            ["commented on", "video."],
            ["commented on", "post."],
            ["commented on", "photo."],
            ["posted a comment on the post by", "."],
            # de
            ["hat auf", "Kommentar geantwortet."],
            ["hat", "Foto kommentiert."],
            ["hat", "Beitrag kommentiert."],
            ["hat", "Video kommentiert."],
            ["hat", "eigenen Beitrag kommentiert."]
        ]
        entry[comment_field] = fb_anonymize_generic(entry[comment_field], sep_strings)
    elif comment_field.__contains__('.'):
        entry = await unravel_hierarchical_fields(entry, comment_field, fb_anonymize_comments)
    return entry


async def fb_anonymize_usernames(entry: typing.Dict[str, typing.Any], username_field: str = '') \
        -> typing.Dict[str, typing.Any]:
    if username_field in entry:
        if entry[username_field] not in fb_list_usernames:
            entry[username_field] = '<user>'
    elif username_field.__contains__('.'):
        entry = await unravel_hierarchical_fields(entry, username_field, fb_anonymize_usernames)
    return entry
