FROM python:3.9.7-buster

EXPOSE 8443

ENV OSD2F_SECRET=""
ENV OSD2F_MODE="Survey"
ENV OSD2F_DB_URL="sqlite:///osd2f/mount/osd2f.sqlite"
ENV OSD2F_SURVEY_TOKEN=""

# make code available
COPY ./ /osd2f
WORKDIR /osd2f

# setup dependencies
RUN apt-get update && apt-get install -yfq sqlite3 git

# OSD2F
RUN git clone https://github.com/datenfruehstueck/osd2f
WORKDIR /osd2f
RUN pip install ./
RUN mkdir mount
RUN sqlite3 mount/osd2f.sqlite

# minimal check to make sure the install works
RUN osd2f --dry-run

# set the default command for the container (i.e. running production)
# all logging outputs will be written to the Docker log
CMD [ "hypercorn", "--keyfile", "mount/key.pem", "--certfile", "mount/cert.pem", "-b", "0.0.0.0:8443", "--access-log", "-", "--error-log", "-", "osd2f.__main__:app" ]
