FROM python:3.9.7-buster

EXPOSE 8443

ENV OSD2F_SECRET=""
ENV OSD2F_MODE="Survey"
ENV OSD2F_DB_URL="sqlite:///osd2f/mount/osd2f.sqlite"
ENV OSD2F_SURVEY_TOKEN=""

# make code available
COPY ./ /osd2f
WORKDIR /osd2f

# setup dependencies
RUN mkdir mount
RUN pip install ./
RUN apt-get update && apt-get install -yfq sqlite3
RUN sqlite3 mount/osd2f.sqlite

# minimal check to make sure the install works
RUN osd2f --dry-run

# set the default command for the container (i.e. running production)
CMD [ "hypercorn", "--keyfile", "mount/key.pem", "--certfile", "mount/cert.pem", "-b", "0.0.0.0:8443", "osd2f.__main__:app" ]
